name: labeler

on:
  pull_request:
    types: [opened]

jobs:
  labeler:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Label the PR action
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label the PR size
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: '10'
          s_max_size: '100'
          m_max_size: '500'
          l_max_size: '1000'
          fail_if_xl: 'false'
          message_if_xl: 'This PR is so big! Please, split it 😊'
